# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: x-salmon.Shellby
PackageVersion: 0.18.0
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/x-salmon/shellby/releases/download/v0.18.0/Shellby-Setup-0.18.0.exe
  InstallerSha256: 493897A8EE7640BB93CD80D391952F314F4814EF5BAF3778086F9A93F3EA32A9
  AppsAndFeaturesEntries:
  - ProductCode: d01bce7a-6b6a-53c0-9edc-a2fd643590df
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-02
